-- 코드를 입력하세요
SELECT C.AUTHOR_ID, C.AUTHOR_NAME, B.CATEGORY, SUM(A.SALES * B.PRICE) AS TOTAL_SALES
FROM BOOK_SALES A, BOOK B, AUTHOR C
WHERE A.BOOK_ID = B.BOOK_ID
AND B.AUTHOR_ID = C.AUTHOR_ID
AND (A.SALES_DATE >= '2022-01-01' AND A.SALES_DATE < '2022-02-01')
GROUP BY C.AUTHOR_ID, C.AUTHOR_NAME, B.CATEGORY
ORDER BY C.AUTHOR_ID, B.CATEGORY DESC