-- 코드를 입력하세요
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(B.PRICE * C.SALES) AS TOTAL_SALES
FROM AUTHOR A
     JOIN BOOK B ON A.AUTHOR_ID = B.AUTHOR_ID
     JOIN BOOK_SALES C ON B.BOOK_ID = C.BOOK_ID
WHERE C.SALES_DATE >= '2022-01-01' AND C.SALES_DATE < '2022-02-01'
GROUP BY A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY A.AUTHOR_ID, B.CATEGORY DESC