-- 코드를 입력하세요
SELECT A.CART_ID
FROM (
    SELECT CART_ID, NAME
    FROM CART_PRODUCTS 
    WHERE NAME IN ('Milk', 'Yogurt')
    GROUP BY CART_ID, NAME
) A
GROUP BY A.CART_ID HAVING COUNT(*) >= 2
ORDER BY A.CART_ID