-- 코드를 작성해주세요
WITH 
ECOLI_FIRST AS (
    SELECT ID, PARENT_ID
    FROM ECOLI_DATA 
    WHERE PARENT_ID IS NULL 
),
ECOLI_SECOND AS (
    SELECT ID, PARENT_ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IN (
        SELECT ID FROM ECOLI_FIRST
    )
)
SELECT ID
FROM ECOLI_DATA 
WHERE PARENT_ID IN (
    SELECT ID 
    FROM ECOLI_SECOND
)
ORDER BY ID;