-- 코드를 작성해주세요
SELECT A.ID, IF(B.PARENT_ID IS NULL, 0, COUNT(B.PARENT_ID)) AS CHILD_COUNT
FROM ECOLI_DATA A LEFT JOIN (
    SELECT PARENT_ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
) B ON A.ID = B.PARENT_ID
GROUP BY A.ID
ORDER BY A.ID