-- 코드를 작성해주세요
SELECT A.ID, IFNULL(B.COUNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA A 
     LEFT JOIN ( SELECT PARENT_ID AS ID, COUNT(*) AS COUNT
                 FROM ECOLI_DATA 
                 WHERE PARENT_ID IS NOT NULL
                 GROUP BY PARENT_ID ) B ON A.ID = B.ID
ORDER BY ID;
