-- 코드를 입력하세요
WITH RENT_INFO AS (
    SELECT B.CAR_ID
    FROM CAR_RENTAL_COMPANY_CAR A
         JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B ON A.CAR_ID = B.CAR_ID
    WHERE A.CAR_TYPE IN ('세단', 'SUV')
    AND B.START_DATE < '2022-12-01' AND B.END_DATE >= '2022-11-01'
    GROUP BY B.CAR_ID
)
SELECT X.CAR_ID, X.CAR_TYPE, X.FEE
FROM (
    SELECT  A.CAR_ID, A.CAR_TYPE,
            FLOOR((A.DAILY_FEE - (A.DAILY_FEE * 
            ((SELECT P.DISCOUNT_RATE
                    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
                    WHERE P.DURATION_TYPE = '30일 이상'
                    AND P.CAR_TYPE = A.CAR_TYPE) / 100))) * 30) AS FEE
    FROM CAR_RENTAL_COMPANY_CAR A
    WHERE A.CAR_TYPE IN ('세단', 'SUV')
    AND A.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM RENT_INFO
    )
) X
WHERE X.FEE BETWEEN 500000 AND 2000000
ORDER BY X.FEE DESC, X.CAR_TYPE, X.CAR_ID DESC

-- 자동차 종류가 '세단' 또는 'SUV' 인 자동차 중
-- 2022년 11월 1일부터 2022년 11월 30일까지 대여 가능