-- 코드를 입력하세요
SELECT Z.CAR_ID, Z.CAR_TYPE, Z.FEE
FROM (
    SELECT X.CAR_ID,
           X.CAR_TYPE,
           (X.DAILY_FEE * 30) - FLOOR((X.DAILY_FEE * 30) *
           (SELECT DISCOUNT_RATE / 100
           FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
           WHERE DURATION_TYPE = '30일 이상' 
           AND CAR_TYPE = X.CAR_TYPE)) AS FEE
    FROM CAR_RENTAL_COMPANY_CAR X
    WHERE X.CAR_ID NOT IN (
        SELECT A.CAR_ID
        FROM CAR_RENTAL_COMPANY_CAR A, CAR_RENTAL_COMPANY_RENTAL_HISTORY B
        WHERE A.CAR_ID = B.CAR_ID
        AND (
             DATEDIFF(B.START_DATE, '2022-12-01') < 0 AND
             DATEDIFF(B.END_DATE, '2022-11-01') >= 0
        )
    )
    AND X.CAR_TYPE IN ('세단', 'SUV')
) Z
WHERE Z.FEE >= 500000 AND Z.FEE < 2000000
ORDER BY Z.FEE DESC, Z.CAR_TYPE, Z.CAR_ID DESC;
