-- 코드를 입력하세요
WITH RENT_INFO AS (
    SELECT A.CAR_ID
    FROM CAR_RENTAL_COMPANY_CAR A, CAR_RENTAL_COMPANY_RENTAL_HISTORY B
    WHERE A.CAR_ID = B.CAR_ID
    AND A.CAR_TYPE IN ('세단', 'SUV')
    AND (B.START_DATE <= '2022-11-30' AND B.END_DATE >= '2022-11-01')
)
SELECT  A.CAR_ID, A.CAR_TYPE, 
        FLOOR(((A.DAILY_FEE - (A.DAILY_FEE * (A.DISCOUNT_RATE / 100))) * 30)) AS FEE
FROM (
        SELECT X.*, Y.DISCOUNT_RATE
        FROM CAR_RENTAL_COMPANY_CAR X, CAR_RENTAL_COMPANY_DISCOUNT_PLAN Y
        WHERE X.CAR_TYPE = Y.CAR_TYPE
        AND Y.DURATION_TYPE = '30일 이상'
     ) A
WHERE A.CAR_TYPE IN ('세단', 'SUV')
AND A.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM RENT_INFO
)
AND ((A.DAILY_FEE - (A.DAILY_FEE * (A.DISCOUNT_RATE / 100))) * 30) >= 500000
AND ((A.DAILY_FEE - (A.DAILY_FEE * (A.DISCOUNT_RATE / 100))) * 30) < 2000000
ORDER BY FEE DESC, A.CAR_TYPE, A.CAR_ID DESC
