-- 코드를 입력하세요
SELECT  USER_ID, 
        NICKNAME, 
        CONCAT(CITY, " " ,STREET_ADDRESS1," " , STREET_ADDRESS2) AS '전체주소', 
        CONCAT(SUBSTRING(TLNO, 1, 3), "-", SUBSTRING(TLNO, 4, 4), "-", SUBSTRING(TLNO, 8, 4)) AS '전화번호'
FROM USED_GOODS_USER 
WHERE USER_ID IN (
    SELECT A.USER_ID
    FROM USED_GOODS_USER A, USED_GOODS_BOARD B
    WHERE A.USER_ID = B.WRITER_ID
    GROUP BY A.USER_ID HAVING COUNT(*) >= 3
)
ORDER BY USER_ID DESC;