-- 코드를 입력하세요
WITH JOIN_STATS AS (
    SELECT COUNT(*) AS JOIN_COUNT
    FROM USER_INFO
    WHERE JOINED LIKE '2021%'
)
SELECT  X.YEAR, X.MONTH, 
        COUNT(*) AS PURCHASED_USERS, 
        ROUND((COUNT(*) / (SELECT JOIN_COUNT FROM JOIN_STATS)), 1) AS PUCHASED_RATIO
FROM (
    SELECT A.USER_ID, YEAR(B.SALES_DATE) AS YEAR, MONTH(B.SALES_DATE) AS MONTH, COUNT(*)
    FROM USER_INFO A, ONLINE_SALE B
    WHERE A.USER_ID = B.USER_ID
    AND A.JOINED LIKE '2021%'
    GROUP BY A.USER_ID, YEAR(B.SALES_DATE), MONTH(B.SALES_DATE)
) X
GROUP BY X.YEAR, X.MONTH
ORDER BY X.YEAR, X.MONTH;
