-- 코드를 입력하세요
WITH JOIN_COUNT AS (
    SELECT COUNT(*) AS COUNT
    FROM USER_INFO 
    WHERE JOINED >= '2021-01-01' AND JOINED < '2022-01-01'
    GROUP BY YEAR(JOINED)
)
SELECT  YEAR(B.SALES_DATE) AS YEAR, 
        MONTH(B.SALES_DATE) AS MONTH, 
        COUNT(DISTINCT(A.USER_ID)) AS PURCHASED_USERS,
        ROUND((COUNT(DISTINCT(A.USER_ID)) / (SELECT COUNT FROM JOIN_COUNT)), 1) AS PUCHASED_RATIO
FROM USER_INFO A, ONLINE_SALE B
WHERE A.USER_ID = B.USER_ID
AND A.JOINED >= '2021-01-01' AND A.JOINED < '2022-01-01'
GROUP BY YEAR(B.SALES_DATE), MONTH(B.SALES_DATE)
ORDER BY YEAR, MONTH