-- 코드를 작성해주세요
WITH RECURSIVE GEN_INFO AS (
    SELECT 1 AS GENERATION, ID, PARENT_ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT A.GENERATION + 1, B.ID, B.PARENT_ID
    FROM GEN_INFO A, ECOLI_DATA B
    WHERE A.ID = B.PARENT_ID
)
SELECT COUNT(*) AS COUNT, GENERATION
FROM GEN_INFO
WHERE ID NOT IN (
    SELECT DISTINCT PARENT_ID
    FROM GEN_INFO
    WHERE PARENT_ID IS NOT NULL)
GROUP BY GENERATION
ORDER BY GENERATION;