-- 코드를 입력하세요
SELECT A.CAR_ID,
       IF(
           (SELECT CAR_ID
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
            WHERE START_DATE < '2022-10-17' AND END_DATE >= '2022-10-16'
            AND CAR_ID = A.CAR_ID) IS NULL, '대여 가능', '대여중') AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
GROUP BY A.CAR_ID
ORDER BY A.CAR_ID DESC