-- 코드를 입력하세요
WITH PROCEED_RENT_INFO AS ( 
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE START_DATE <= '2022-10-16' && END_DATE >= '2022-10-16'
)
SELECT  A.CAR_ID,
        CASE
            WHEN B.CAR_ID IS NOT NULL THEN '대여중'
            ELSE '대여 가능'
        END AS 'AVAILABILITY'
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
     LEFT JOIN PROCEED_RENT_INFO B ON A.CAR_ID = B.CAR_ID
GROUP BY A.CAR_ID
ORDER BY A.CAR_ID DESC