-- 코드를 입력하세요
WITH RENT_INFO AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE START_DATE <= '2022-10-16' AND END_DATE >= '2022-10-16'
)
SELECT A.CAR_ID, IF(B.CAR_ID IS NULL, '대여 가능', '대여중') AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
     LEFT JOIN RENT_INFO B ON A.CAR_ID = B.CAR_ID
GROUP BY A.CAR_ID
ORDER BY A.CAR_ID DESC