-- 코드를 입력하세요
WITH HEAVY_USER AS (
    SELECT HOST_ID
    FROM PLACES 
    GROUP BY HOST_ID HAVING COUNT(*) >= 2
)
SELECT ID, NAME, HOST_ID
FROM PLACES
WHERE HOST_ID IN (SELECT HOST_ID FROM HEAVY_USER)
ORDER BY ID