-- 코드를 입력하세요
WITH TRUCK_DISCOUNT_INFO AS (
    SELECT DURATION_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = '트럭' 
)
SELECT  A.HISTORY_ID,
        FLOOR(((B.DAILY_FEE - (B.DAILY_FEE * (CASE
            WHEN DATEDIFF(A.END_DATE, A.START_DATE) + 1 >= 90 
                THEN (SELECT DISCOUNT_RATE / 100 FROM TRUCK_DISCOUNT_INFO WHERE DURATION_TYPE = '90일 이상')
            WHEN DATEDIFF(A.END_DATE, A.START_DATE) + 1 >= 30
                THEN (SELECT DISCOUNT_RATE / 100 FROM TRUCK_DISCOUNT_INFO WHERE DURATION_TYPE = '30일 이상')
            WHEN DATEDIFF(A.END_DATE, A.START_DATE) + 1 >= 7
                THEN (SELECT DISCOUNT_RATE / 100 FROM TRUCK_DISCOUNT_INFO WHERE DURATION_TYPE = '7일 이상')
            ELSE 0
        END))) * (DATEDIFF(A.END_DATE, A.START_DATE) + 1))) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
     JOIN CAR_RENTAL_COMPANY_CAR B ON A.CAR_ID = B.CAR_ID
WHERE B.CAR_TYPE = '트럭'
ORDER BY FEE DESC, A.HISTORY_ID DESC