-- 코드를 입력하세요
# SELECT Y.HISTORY_ID, ((Y.DAILY_FEE * Y.DURATION) - X.DISCOUNT_RATE / 100) AS FEE
# FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN X (
#     SELECT  B.HISTORY_ID, A.DAILY_FEE, 
#             (DATEDIFF(B.END_DATE, B.START_DATE) + 1) AS 'DURATION',
#             CASE
#                 WHEN (DATEDIFF(B.END_DATE, B.START_DATE) + 1) >= 90 THEN '90일 이상'
#                 WHEN (DATEDIFF(B.END_DATE, B.START_DATE) + 1) >= 30 THEN '30일 이상'
#                 WHEN (DATEDIFF(B.END_DATE, B.START_DATE) + 1) >= 7 THEN '7일 이상'
#                 ELSE ''
#             END AS 'DURATION_TYPE'
#     FROM CAR_RENTAL_COMPANY_CAR A, CAR_RENTAL_COMPANY_RENTAL_HISTORY B
#     WHERE A.CAR_ID = B.CAR_ID
#     AND A.CAR_TYPE = '트럭') Y
# WHERE X.DURATION_TYPE = Y.DURATION_TYPE
# AND X.CAR_TYPE = '트럭'
# ORDER BY FEE DESC, Y.HISTORY_ID DESC


WITH TRUCK_PLAN AS (
    SELECT DURATION_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = '트럭'
)
SELECT  B.HISTORY_ID,
        FLOOR(((A.DAILY_FEE) - ((A.DAILY_FEE) * 
                 IFNULL((SELECT DISCOUNT_RATE
                         FROM TRUCK_PLAN 
                         WHERE DURATION_TYPE = B.DURATION_TYPE), 0) / 100)) * B.DURATION) AS FEE
FROM CAR_RENTAL_COMPANY_CAR A, (
    SELECT  HISTORY_ID, CAR_ID,
            (DATEDIFF(END_DATE, START_DATE) + 1) AS 'DURATION',
            CASE
                WHEN (DATEDIFF(END_DATE, START_DATE) + 1) >= 90 THEN '90일 이상'
                WHEN (DATEDIFF(END_DATE, START_DATE) + 1) >= 30 THEN '30일 이상'
                WHEN (DATEDIFF(END_DATE, START_DATE) + 1) >= 7 THEN '7일 이상'
                ELSE ''
            END AS 'DURATION_TYPE' 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY ) B
WHERE A.CAR_ID = B.CAR_ID
AND A.CAR_TYPE = '트럭'
ORDER BY FEE DESC, B.HISTORY_ID DESC;


-- SELECT * FROM CAR_RENTAL_COMPANY_CAR WHERE car_id = 20; -- 168000
-- SELECT * FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE HISTORY_ID = 630;
-- SELECT * FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN ;

# SELECT COUNT(*)
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
# WHERE CAR_ID IN (
# SELECT CAR_ID FROM CAR_RENTAL_COMPANY_CAR WHERE CAR_TYPE = '트럭'
# );

# (SELECT  B.HISTORY_ID, 
#         CASE
#             WHEN (DATEDIFF(B.END_DATE, B.START_DATE) + 1) >= 90 THEN '90일 이상'
#             WHEN (DATEDIFF(B.END_DATE, B.START_DATE) + 1) >= 30 THEN '30일 이상'
#             WHEN (DATEDIFF(B.END_DATE, B.START_DATE) + 1) >= 7 THEN '7일 이상'
#             ELSE ''
#         END AS 'DURATION_TYPE'
# FROM CAR_RENTAL_COMPANY_CAR A, CAR_RENTAL_COMPANY_RENTAL_HISTORY B
# WHERE A.CAR_ID = B.CAR_ID
# AND A.CAR_TYPE = '트럭')
