-- 코드를 입력하세요
SELECT A.APNT_NO, 
       (SELECT PT_NAME FROM PATIENT WHERE PT_NO = A.PT_NO) AS PT_NAME, 
       A.PT_NO, 
       A.MCDP_CD, 
       (SELECT DR_NAME FROM DOCTOR WHERE DR_ID = A.MDDR_ID) AS DR_NAME, 
       A.APNT_YMD
FROM APPOINTMENT A
WHERE A.APNT_YMD >= '2022-04-13 00:00:00' AND A.APNT_YMD < '2022-04-14 00:00:00'
AND A.APNT_CNCL_YN = 'N'
AND A.MCDP_CD = 'CS'
ORDER BY A.APNT_YMD;