-- 코드를 입력하세요
SELECT C.APNT_NO, A.PT_NAME, A.PT_NO, B.MCDP_CD, B.DR_NAME, C.APNT_YMD
FROM PATIENT A, DOCTOR B, APPOINTMENT C
WHERE A.PT_NO = C.PT_NO
AND C.MDDR_ID = B.DR_ID
AND C.APNT_CNCL_YN = 'N'
AND (C.APNT_YMD >= '2022-04-13 00:00:00' AND C.APNT_YMD < '2022-04-14 00:00:00')
AND B.MCDP_CD = 'CS'
ORDER BY C.APNT_YMD