-- 코드를 입력하세요
SELECT A.APNT_NO, B.PT_NAME, B.PT_NO, A.MCDP_CD, C.DR_NAME, A.APNT_YMD
FROM APPOINTMENT A
     LEFT JOIN PATIENT B ON A.PT_NO = B.PT_NO
     LEFT JOIN DOCTOR C ON A.MDDR_ID = C.DR_ID
WHERE (A.APNT_YMD >= '2022-04-13 00:00:00' AND A.APNT_YMD < '2022-04-14 00:00:00')
AND A.APNT_CNCL_YN = 'N'
AND A.MCDP_CD = 'CS'
ORDER BY A.APNT_YMD