-- 코드를 입력하세요
WITH RECURSIVE HOUR_INFO AS (
    SELECT 0 AS HOUR
    UNION
    SELECT HOUR + 1 AS HOUR
    FROM HOUR_INFO
    WHERE HOUR < 23
)
-- 참고) COUNT(*)로 하면 ANIMAL_OUTS에 없는 것도 카운트 됨. (그림 그려보자.)
SELECT B.HOUR, COUNT(A.ANIMAL_ID) AS COUNT
FROM ANIMAL_OUTS A 
     RIGHT OUTER JOIN HOUR_INFO B ON HOUR(A.DATETIME) = B.HOUR
-- 참고) GROUP BY HOUR(A.DATETIME)으로 하면 ANIMAL_OUTS에 없는 시간대는 결과에서 사라짐. 
GROUP BY B.HOUR
ORDER BY B.HOUR