-- 코드를 입력하세요
WITH RECURSIVE HOUR_INFO AS (
    SELECT 0 AS HOUR
    UNION
    SELECT HOUR + 1 AS HOUR
    FROM HOUR_INFO
    WHERE HOUR < 23
)
SELECT B.HOUR, COUNT(A.ANIMAL_ID) AS COUNT
FROM ANIMAL_OUTS A 
     RIGHT OUTER JOIN HOUR_INFO B ON HOUR(A.DATETIME) = B.HOUR

GROUP BY B.HOUR
ORDER BY B.HOUR