-- 코드를 입력하세요
SELECT A.USER_ID, A.NICKNAME, SUM(B.PRICE) AS 'TOTAL_SALES'
FROM USED_GOODS_USER A, USED_GOODS_BOARD B
WHERE A.USER_ID = B.WRITER_ID
AND B.STATUS = 'DONE'
GROUP BY A.USER_ID HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES;