-- 코드를 작성해주세요
WITH RARE_ITEM AS (
    SELECT ITEM_ID
    FROM ITEM_INFO
    WHERE RARITY = 'RARE'
)
SELECT A.ITEM_ID, A.ITEM_NAME, A.RARITY
FROM ITEM_INFO A, ITEM_TREE B
WHERE A.ITEM_ID = B.ITEM_ID
AND B.PARENT_ITEM_ID IN (
    SELECT ITEM_ID
    FROM RARE_ITEM
)
ORDER BY A.ITEM_ID DESC

