-- 코드를 작성해주세요
WITH PARENT_INFO AS (
    SELECT ID, GENOTYPE
    FROM ECOLI_DATA 
)
SELECT A.ID, A.GENOTYPE, B.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA A, PARENT_INFO B 
WHERE A.PARENT_ID = B.ID
AND (A.GENOTYPE & B.GENOTYPE) = B.GENOTYPE
ORDER BY A.ID