-- 코드를 작성해주세요
WITH MAX_YEAR_ECOLI_DATA AS (
    SELECT  YEAR(DIFFERENTIATION_DATE) AS DIFFERENTIATION_YEAR, 
            MAX(SIZE_OF_COLONY) AS SIZE_OF_COLONY
    FROM ECOLI_DATA
    GROUP BY DIFFERENTIATION_YEAR
)
SELECT YEAR(A.DIFFERENTIATION_DATE) AS YEAR, (B.SIZE_OF_COLONY - A.SIZE_OF_COLONY) AS YEAR_DEV, A.ID
FROM ECOLI_DATA A, MAX_YEAR_ECOLI_DATA B
WHERE YEAR(A.DIFFERENTIATION_DATE) = B.DIFFERENTIATION_YEAR
ORDER BY YEAR, YEAR_DEV
