-- 코드를 작성해주세요
WITH SIZE_BY_YEAR AS (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS SIZE_OF_COLONY
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)
SELECT YEAR(A.DIFFERENTIATION_DATE) AS YEAR, 
       ((SELECT SIZE_OF_COLONY 
        FROM SIZE_BY_YEAR 
        WHERE YEAR = YEAR(A.DIFFERENTIATION_DATE)) - SIZE_OF_COLONY) AS YEAR_DEV,
       A.ID
FROM ECOLI_DATA A
ORDER BY 1, 2;
