-- 코드를 작성해주세요
WITH MAX_FISH_INFO AS (
    SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)
SELECT A.ID, B.FISH_NAME, A.LENGTH
FROM FISH_INFO A, FISH_NAME_INFO B, MAX_FISH_INFO C
WHERE A.FISH_TYPE = B.FISH_TYPE
AND B.FISH_TYPE = C.FISH_TYPE
AND A.LENGTH = C.LENGTH
ORDER BY A.ID

