-- 코드를 작성해주세요
WITH MAX_FISH_INFO AS (
    SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)
SELECT A.ID, B.FISH_NAME, A.LENGTH
FROM FISH_INFO A, FISH_NAME_INFO B
WHERE A.FISH_TYPE = B.FISH_TYPE
AND (A.FISH_TYPE, A.LENGTH) IN (
    SELECT FISH_TYPE, LENGTH
    FROM MAX_FISH_INFO
)
ORDER BY A.ID