-- 코드를 작성해주세요
SELECT SUM(C.SCORE) AS SCORE, B.EMP_NO, B.EMP_NAME, B.POSITION, B.EMAIL
FROM HR_EMPLOYEES B, HR_GRADE C
WHERE B.EMP_NO = C.EMP_NO
AND C.YEAR = '2022'
GROUP BY C.EMP_NO
ORDER BY SUM(C.SCORE) DESC
LIMIT 0, 1;