-- 코드를 작성해주세요
SELECT SUM(SCORE) AS SCORE, B.EMP_NO, B.EMP_NAME, B.POSITION, B.EMAIL
FROM HR_DEPARTMENT A
     JOIN HR_EMPLOYEES B ON A.DEPT_ID = B.DEPT_ID
     JOIN HR_GRADE C ON B.EMP_NO = C.EMP_NO
GROUP BY B.EMP_NO
ORDER BY SCORE DESC
LIMIT 0, 1