-- 코드를 입력하세요
SELECT CATEGORY, PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE (CATEGORY, PRICE) IN (
    SELECT CATEGORY, MAX(PRICE)
    FROM FOOD_PRODUCT 
    WHERE CATEGORY IN ('식용유', '국', '김치', '과자')
    GROUP BY CATEGORY
)
ORDER BY PRICE DESC