-- 코드를 작성해주세요
SELECT A.GRADE, A.ID, A.EMAIL
FROM (
    SELECT
         CASE 
             WHEN SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') != 0 &&
                  SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End') != 0 THEN 'A'
             WHEN SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') THEN 'B'
             WHEN SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End') THEN 'C' 
             ELSE 'NONE'
         END AS 'GRADE',
         ID,
         EMAIL
    FROM DEVELOPERS 
) A
WHERE A.GRADE != 'NONE'
ORDER BY GRADE, ID