-- 코드를 입력하세요
SELECT  IF (A.PRICE = '0', '0', CONCAT(A.PRICE, '0000')) AS PRICE_GROUP, COUNT(*) AS PRODUCTS
FROM (
    SELECT FLOOR(PRICE / 10000) AS PRICE
    FROM PRODUCT
) A
GROUP BY PRICE
ORDER BY PRICE_GROUP;

